version: 0.0
os: linux
files:
  - source: /
    destination: /var/www/html/your-app
hooks:
  BeforeInstall:
    - location: scripts/stop_apache.sh
      timeout: 300
      runas: root
  AfterInstall:
    - location: scripts/start_apache.sh
      timeout: 300
      runas: root
