version: 0.0
os: linux
files:
  - source: /
    destination: /var/www/html/rv-tampa.com
hooks:
  BeforeInstall:
    - location: scripts/stop_apache.sh
      timeout: 300
      runas: root      
  AfterInstall:
    - location: scripts/start_apache.sh
      timeout: 300
      runas: root
  # ApplicationStart:    
  #   - location: scripts/set_laravel_permissions.sh  
  #     timeout: 300
  #     runas: root    
  #   - location: scripts/php_artisian_optimize.sh  
  #     timeout: 300
  #     runas: root 